# Database Configuration
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/accounts?useUnicode=true&characterEncoding=UTF-8
jdbc.username=vprofile
jdbc.password=Admin@12345

# RabbitMQ Configuration
rabbitmq.address=localhost
rabbitmq.port=5672
rabbitmq.username=vprofile_mq
rabbitmq.password=RabbitMq@Secure#2024

# Memcached Configuration
# Memcached Active Server
memcached.active.host=localhost
memcached.active.port=11211
# Memcached Standby Server (for single VM, use same server)
memcached.standBy.host=localhost
memcached.standBy.port=11211

# Elasticsearch Configuration
elasticsearch.cluster=elasticsearch
elasticsearch.node=localhost
elasticsearch.host=localhost
elasticsearch.port=9200
